[package]
name = "simd256"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# core_simd = { git = "https://github.com/rust-lang/portable-simd" }

[dev-dependencies]
num-bigint = "0.4"
rand = "0.8"
